# Generated by Django 5.2.6 on 2025-10-02 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(default='fas fa-file-alt', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='primary', max_length=20, verbose_name='Color')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Formulario',
                'verbose_name_plural': 'Categorías de Formularios',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('file', models.FileField(upload_to='forms/documents/', verbose_name='Archivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('file_type', models.CharField(blank=True, max_length=10, verbose_name='Tipo de archivo')),
                ('required_permission', models.CharField(choices=[('admin', 'Solo Administradores'), ('hr', 'Recursos Humanos'), ('management', 'Gerencia'), ('supervisor', 'Supervisores'), ('all', 'Todos los empleados')], default='hr', max_length=20, verbose_name='Permiso requerido')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_fillable', models.BooleanField(default=False, verbose_name='Formulario rellenable')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Descargas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formcategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Descargado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formdocument', verbose_name='Formulario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Descarga',
                'verbose_name_plural': 'Logs de Descargas',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
