# Generated by Django 5.2.6 on 2025-10-02 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdownloadlog',
            name='downloaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='formdownloadlog',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='forms.formdocument'),
        ),
        migrations.AlterField(
            model_name='formdownloadlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, default='127.0.0.1', null=True),
        ),
        migrations.AlterField(
            model_name='formdownloadlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formdownloadlog',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versión')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Requiere Aprobación')),
                ('allow_draft', models.BooleanField(default=True, verbose_name='Permitir Borrador')),
                ('required_permission', models.CharField(choices=[('admin', 'Solo Administradores'), ('hr', 'Recursos Humanos'), ('management', 'Gerencia'), ('supervisor', 'Supervisores'), ('all', 'Todos los empleados')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission_count', models.PositiveIntegerField(default=0, verbose_name='Envíos')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formcategory', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Formulario',
                'verbose_name_plural': 'Plantillas de Formularios',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('submitted', 'Enviado'), ('under_review', 'En Revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('completed', 'Completado')], default='draft', max_length=20, verbose_name='Estado')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_data', models.JSONField(default=dict, verbose_name='Datos del Formulario')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('review_comments', models.TextField(blank=True, verbose_name='Comentarios de Revisión')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Archivos Adjuntos')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_forms', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_forms', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.formtemplate')),
            ],
            options={
                'verbose_name': 'Envío de Formulario',
                'verbose_name_plural': 'Envíos de Formularios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Campo')),
                ('label', models.CharField(max_length=200, verbose_name='Etiqueta')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('textarea', 'Área de Texto'), ('email', 'Email'), ('number', 'Número'), ('date', 'Fecha'), ('checkbox', 'Checkbox'), ('radio', 'Radio Button'), ('select', 'Lista Desplegable'), ('file', 'Archivo'), ('signature', 'Firma Digital')], max_length=20, verbose_name='Tipo')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Placeholder')),
                ('help_text', models.CharField(blank=True, max_length=300, verbose_name='Texto de Ayuda')),
                ('is_required', models.BooleanField(default=False, verbose_name='Requerido')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longitud Mínima')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Longitud Máxima')),
                ('choices', models.JSONField(blank=True, default=list, verbose_name='Opciones')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('section', models.CharField(blank=True, max_length=100, verbose_name='Sección')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.formtemplate')),
            ],
            options={
                'verbose_name': 'Campo de Formulario',
                'verbose_name_plural': 'Campos de Formulario',
                'ordering': ['template', 'order', 'name'],
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10)),
                ('instructions', models.TextField(blank=True, verbose_name='Instrucciones')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_forms_to_complete', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment', to='forms.formsubmission')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='forms.formtemplate')),
            ],
            options={
                'verbose_name': 'Asignación de Formulario',
                'verbose_name_plural': 'Asignaciones de Formularios',
                'ordering': ['-created_at'],
                'unique_together': {('template', 'assigned_to', 'assigned_by')},
            },
        ),
    ]
