# Generated by Django 5.2.6 on 2025-09-22 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('title', models.CharField(max_length=100, verbose_name='Título del Puesto')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Código')),
                ('description', models.TextField(verbose_name='Descripción del Puesto')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Mínimo')),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Máximo')),
                ('level', models.CharField(choices=[('ENTRY', 'Nivel de Entrada'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('LEAD', 'Líder'), ('MANAGER', 'Gerente'), ('DIRECTOR', 'Director')], max_length=20, verbose_name='Nivel')),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Tiempo Completo'), ('PART_TIME', 'Medio Tiempo'), ('CONTRACT', 'Contrato'), ('TEMPORARY', 'Temporal')], max_length=20, verbose_name='Tipo de Empleo')),
                ('max_positions', models.PositiveIntegerField(default=1, verbose_name='Máximo de Puestos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_hiring', models.BooleanField(default=False, verbose_name='En Proceso de Contratación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='departments.department', verbose_name='Departamento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Puesto de Trabajo',
                'verbose_name_plural': 'Puestos de Trabajo',
                'ordering': ['department__name', 'title'],
            },
        ),
    ]
