# Generated by Django 5.2.6 on 2025-10-02 23:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_alter_department_department_type'),
        ('employees', '0002_alter_employee_address_alter_employee_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('category_type', models.CharField(choices=[('OPERATIVO', 'Riesgos Operativos'), ('TECNOLOGICO', 'Riesgos Tecnológicos'), ('CAPITAL_HUMANO', 'Riesgos de Capital Humano'), ('ENTORNO', 'Riesgos del Entorno y Externos'), ('REPUTACIONAL', 'Riesgos Reputacionales')], max_length=20, verbose_name='Tipo de Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6c757d', help_text='Color en formato HEX (#RRGGBB)', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='fa-exclamation-triangle', help_text='Icono de FontAwesome', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría de Riesgo',
                'verbose_name_plural': 'Categorías de Riesgos',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: RSG-001', max_length=20, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=200, verbose_name='Riesgo')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('probability', models.IntegerField(help_text='1=Muy Bajo, 2=Bajo, 3=Medio, 4=Alto, 5=Muy Alto', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Probabilidad (1-5)')),
                ('impact', models.IntegerField(help_text='1=Muy Bajo, 2=Bajo, 3=Medio, 4=Alto, 5=Muy Alto', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Impacto (1-5)')),
                ('risk_score', models.IntegerField(editable=False, verbose_name='Nivel de Riesgo (P×I)')),
                ('risk_level', models.CharField(choices=[('BAJO', 'Bajo (1-6)'), ('MEDIO', 'Medio (7-14)'), ('ALTO', 'Alto (15-25)')], editable=False, max_length=10, verbose_name='Nivel de Riesgo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_mitigated', models.BooleanField(default=False, verbose_name='Mitigado')),
                ('mitigation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Mitigación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('last_review_date', models.DateField(blank=True, null=True, verbose_name='Última Revisión')),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Próxima Revisión')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Departamento Afectado')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_risks', to='employees.employee', verbose_name='Responsable')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='quality_control.riskcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
                'ordering': ['-risk_score', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ControlMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Medida de Control')),
                ('description', models.TextField(verbose_name='Descripción Detallada')),
                ('priority', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Completación')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Estimado')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Real')),
                ('effectiveness_score', models.IntegerField(blank=True, help_text='Calificación de la efectividad de la medida', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Efectividad (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_measures', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_measures', to='employees.employee', verbose_name='Responsable')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_measures', to='quality_control.risk', verbose_name='Riesgo')),
            ],
            options={
                'verbose_name': 'Medida de Control',
                'verbose_name_plural': 'Medidas de Control',
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Evaluación')),
                ('probability', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Probabilidad')),
                ('impact', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Impacto')),
                ('risk_score', models.IntegerField(editable=False, verbose_name='Puntuación')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recommendations', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Evaluado por')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='quality_control.risk', verbose_name='Riesgo')),
            ],
            options={
                'verbose_name': 'Evaluación de Riesgo',
                'verbose_name_plural': 'Evaluaciones de Riesgos',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=20, unique=True, verbose_name='Número de Incidente')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Incidente')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('incident_date', models.DateTimeField(verbose_name='Fecha y Hora del Incidente')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('severity', models.CharField(choices=[('MENOR', 'Menor'), ('MODERADO', 'Moderado'), ('GRAVE', 'Grave'), ('CRITICO', 'Crítico')], max_length=10, verbose_name='Severidad')),
                ('financial_impact', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Impacto Financiero')),
                ('operational_impact', models.TextField(blank=True, verbose_name='Impacto Operacional')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelto')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affected_employees', models.ManyToManyField(blank=True, related_name='affected_by_incidents', to='employees.employee', verbose_name='Empleados Afectados')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='employees.employee', verbose_name='Reportado por')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='quality_control.risk', verbose_name='Riesgo Relacionado')),
            ],
            options={
                'verbose_name': 'Incidente de Riesgo',
                'verbose_name_plural': 'Incidentes de Riesgos',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['risk_level', 'is_active'], name='quality_con_risk_le_f43499_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['category', 'risk_score'], name='quality_con_categor_81fa48_idx'),
        ),
    ]
