# Generated by Django 5.2.6 on 2025-09-22 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('department_type', models.CharField(choices=[('RRHH', 'Recursos Humanos'), ('SISTEMAS', 'Sistemas'), ('OPERACIONES', 'Operaciones'), ('ADMINISTRACION', 'Administración'), ('SEGURIDAD', 'Seguridad Física'), ('FINANZAS', 'Finanzas'), ('LOGISTICA', 'Logística'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20, verbose_name='Tipo de Departamento')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Departamento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Presupuesto Asignado')),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Presupuesto Gastado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_records', to='departments.department')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Presupuesto Departamental',
                'verbose_name_plural': 'Presupuestos Departamentales',
                'ordering': ['-year', '-month'],
                'unique_together': {('department', 'year', 'month')},
            },
        ),
    ]
