# Generated by Django 5.2.6 on 2025-10-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_type',
            field=models.CharField(choices=[('RRHH', 'Recursos Humanos'), ('SISTEMAS', 'Sistemas'), ('MARKETING', 'Marketing y Comunicaciones'), ('DIGITAL', 'Transformación Digital'), ('OPERACIONES', 'Operaciones'), ('ADMINISTRACION', 'Administración'), ('SEGURIDAD', 'Seguridad Física'), ('FINANZAS', 'Finanzas'), ('LOGISTICA', 'Logística'), ('MANTENIMIENTO', 'Mantenimiento'), ('COMERCIAL', 'Comercial y Ventas')], max_length=20, verbose_name='Tipo de Departamento'),
        ),
    ]
