# Generated by Django 5.2.6 on 2025-09-23 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facialrecognitionprofile',
            name='image_1',
            field=models.ImageField(blank=True, help_text='Primera imagen de referencia', null=True, upload_to='facial_profiles/'),
        ),
        migrations.AddField(
            model_name='facialrecognitionprofile',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Segunda imagen de referencia', null=True, upload_to='facial_profiles/'),
        ),
        migrations.AddField(
            model_name='facialrecognitionprofile',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Tercera imagen de referencia', null=True, upload_to='facial_profiles/'),
        ),
        migrations.AddField(
            model_name='facialrecognitionprofile',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Cuarta imagen de referencia (opcional)', null=True, upload_to='facial_profiles/'),
        ),
        migrations.AddField(
            model_name='facialrecognitionprofile',
            name='image_5',
            field=models.ImageField(blank=True, help_text='Quinta imagen de referencia (opcional)', null=True, upload_to='facial_profiles/'),
        ),
        migrations.AlterField(
            model_name='facialrecognitionprofile',
            name='confidence_threshold',
            field=models.FloatField(default=0.75, help_text='Umbral de confianza para reconocimiento (0.0-1.0)'),
        ),
        migrations.AlterField(
            model_name='facialrecognitionprofile',
            name='face_encoding',
            field=models.TextField(blank=True, help_text='Codificación facial serializada en base64'),
        ),
        migrations.AlterField(
            model_name='facialrecognitionprofile',
            name='reference_images',
            field=models.TextField(blank=True, help_text='Metadatos de imágenes de referencia'),
        ),
    ]
