# Generated by Django 5.2.6 on 2025-09-23 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_facialrecognitionprofile_image_1_and_more'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='Precisión GPS (metros)')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitud (metros)')),
                ('tracking_type', models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual'), ('ATTENDANCE', 'Marcación'), ('PATROL', 'Patrullaje'), ('EMERGENCY', 'Emergencia')], default='AUTO', max_length=20, verbose_name='Tipo de Rastreo')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('is_within_work_area', models.BooleanField(default=False, verbose_name='Dentro del Área')),
                ('distance_to_work_area', models.FloatField(blank=True, null=True, verbose_name='Distancia al Área (metros)')),
                ('battery_level', models.IntegerField(blank=True, null=True, verbose_name='Nivel de Batería (%)')),
                ('device_info', models.TextField(blank=True, verbose_name='Información del Dispositivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_active_session', models.BooleanField(default=True, verbose_name='Sesión Activa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_tracking', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Rastreo GPS',
                'verbose_name_plural': 'Rastreos GPS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Área')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('area_type', models.CharField(choices=[('OFFICE', 'Oficina'), ('BUILDING', 'Edificio'), ('MALL', 'Centro Comercial'), ('RESIDENTIAL', 'Residencial'), ('INDUSTRIAL', 'Industrial'), ('PATROL', 'Ronda/Patrullaje'), ('EVENT', 'Evento'), ('OTHER', 'Otro')], max_length=20, verbose_name='Tipo de Área')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('radius_meters', models.IntegerField(default=50, verbose_name='Radio de Cobertura (metros)')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de Contacto')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('requires_attendance', models.BooleanField(default=True, verbose_name='Requiere Marcación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Área de Trabajo',
                'verbose_name_plural': 'Áreas de Trabajo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LocationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('alert_type', models.CharField(choices=[('OUT_OF_AREA', 'Fuera del Área'), ('LATE_ARRIVAL', 'Llegada Tarde'), ('EARLY_DEPARTURE', 'Salida Temprana'), ('NO_MOVEMENT', 'Sin Movimiento'), ('EMERGENCY', 'Emergencia'), ('BATTERY_LOW', 'Batería Baja')], max_length=20, verbose_name='Tipo de Alerta')),
                ('alert_level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica'), ('EMERGENCY', 'Emergencia')], default='WARNING', max_length=20, verbose_name='Nivel de Alerta')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta el')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_alerts', to='employees.employee')),
                ('gps_tracking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.gpstracking')),
                ('notified_supervisors', models.ManyToManyField(blank=True, related_name='received_alerts', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.workarea')),
            ],
            options={
                'verbose_name': 'Alerta de Ubicación',
                'verbose_name_plural': 'Alertas de Ubicación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gpstracking',
            name='work_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workarea'),
        ),
        migrations.CreateModel(
            name='EmployeeWorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Área Principal')),
                ('tolerance_meters', models.IntegerField(default=0, verbose_name='Tolerancia Extra (metros)')),
                ('custom_start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio Personalizada')),
                ('custom_end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin Personalizada')),
                ('monday', models.BooleanField(default=True, verbose_name='Lunes')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Martes')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('thursday', models.BooleanField(default=True, verbose_name='Jueves')),
                ('friday', models.BooleanField(default=True, verbose_name='Viernes')),
                ('saturday', models.BooleanField(default=False, verbose_name='Sábado')),
                ('sunday', models.BooleanField(default=False, verbose_name='Domingo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Asignación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_areas', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('work_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employees', to='attendance.workarea')),
            ],
            options={
                'verbose_name': 'Asignación de Área',
                'verbose_name_plural': 'Asignaciones de Áreas',
            },
        ),
        migrations.AddIndex(
            model_name='gpstracking',
            index=models.Index(fields=['employee', '-timestamp'], name='attendance__employe_46392f_idx'),
        ),
        migrations.AddIndex(
            model_name='gpstracking',
            index=models.Index(fields=['work_area', '-timestamp'], name='attendance__work_ar_14a4e7_idx'),
        ),
        migrations.AddIndex(
            model_name='gpstracking',
            index=models.Index(fields=['is_active_session', '-timestamp'], name='attendance__is_acti_bad941_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeworkarea',
            unique_together={('employee', 'work_area')},
        ),
    ]
