# Generated by Django 5.2.6 on 2025-09-24 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_gpstracking_workarea_locationalert_and_more'),
        ('employees', '0002_alter_employee_address_alter_employee_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpstracking',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gps_tracking', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='gpstracking',
            name='tracking_type',
            field=models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual'), ('ATTENDANCE', 'Marcación'), ('PATROL', 'Patrullaje'), ('EMERGENCY', 'Emergencia'), ('SUPERUSER', 'Superusuario')], default='AUTO', max_length=20, verbose_name='Tipo de Rastreo'),
        ),
    ]
