# Generated by Django 5.2.6 on 2025-09-27 03:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20250923_2130'),
        ('employees', '0002_alter_employee_address_alter_employee_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Plantilla')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('category', models.CharField(choices=[('STANDARD', 'Estándar (8 horas)'), ('EXTENDED', 'Extendido (12 horas)'), ('SECURITY', 'Seguridad (24/7)'), ('OFFICE', 'Oficina'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Categoría')),
                ('shift_type', models.CharField(choices=[('FIXED', 'Turno Fijo'), ('ROTATING', 'Turno Rotativo'), ('FLEXIBLE', 'Horario Flexible'), ('SPLIT', 'Turno Dividido')], max_length=20, verbose_name='Tipo de Turno')),
                ('total_shifts_per_day', models.PositiveIntegerField(default=3, verbose_name='Turnos por Día')),
                ('hours_per_shift', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Horas por Turno')),
                ('rotation_days', models.PositiveIntegerField(default=7, help_text='Cada cuántos días rota el turno', verbose_name='Días de Rotación')),
                ('icon_name', models.CharField(default='fas fa-clock', help_text='Clase CSS del icono FontAwesome', max_length=50, verbose_name='Icono')),
                ('color_primary', models.CharField(default='#3b82f6', max_length=7, verbose_name='Color Primario')),
                ('color_secondary', models.CharField(default='#1e40af', max_length=7, verbose_name='Color Secundario')),
                ('shifts_config', models.TextField(default='[]', help_text='JSON con configuración detallada de cada turno', verbose_name='Configuración de Turnos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Plantilla por Defecto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plantilla de Turno',
                'verbose_name_plural': 'Plantillas de Turnos',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Horario')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('schedule_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('DEPARTMENT', 'Por Departamento'), ('POSITION', 'Por Puesto'), ('GLOBAL', 'Global')], max_length=20, verbose_name='Tipo de Horario')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, help_text='Dejar vacío para horario indefinido', null=True, verbose_name='Fecha de Fin')),
                ('overtime_threshold_daily', models.DecimalField(decimal_places=2, default=8.0, max_digits=4, verbose_name='Umbral Diario Horas Extras')),
                ('overtime_threshold_weekly', models.DecimalField(decimal_places=2, default=40.0, max_digits=4, verbose_name='Umbral Semanal Horas Extras')),
                ('night_shift_start', models.TimeField(default=datetime.time(22, 0), verbose_name='Inicio Turno Nocturno')),
                ('night_shift_end', models.TimeField(default=datetime.time(6, 0), verbose_name='Fin Turno Nocturno')),
                ('night_shift_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=3, verbose_name='Multiplicador Nocturno')),
                ('break_duration_minutes', models.PositiveIntegerField(default=60, verbose_name='Duración Descanso (min)')),
                ('paid_break_minutes', models.PositiveIntegerField(default=15, verbose_name='Descanso Pagado (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='attendance.shifttemplate', verbose_name='Plantilla de Turno')),
            ],
            options={
                'verbose_name': 'Horario de Trabajo',
                'verbose_name_plural': 'Horarios de Trabajo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MORNING', 'Matutino'), ('AFTERNOON', 'Vespertino'), ('NIGHT', 'Nocturno'), ('DAWN', 'Madrugada'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Nombre del Turno')),
                ('custom_name', models.CharField(blank=True, max_length=50, verbose_name='Nombre Personalizado')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Fin')),
                ('is_overnight', models.BooleanField(default=False, help_text='Marca si el turno cruza medianoche', verbose_name='Turno Nocturno')),
                ('break_start_time', models.TimeField(blank=True, null=True, verbose_name='Inicio de Descanso')),
                ('break_end_time', models.TimeField(blank=True, null=True, verbose_name='Fin de Descanso')),
                ('late_tolerance_minutes', models.PositiveIntegerField(default=15, verbose_name='Tolerancia Llegada Tarde (min)')),
                ('early_exit_tolerance_minutes', models.PositiveIntegerField(default=15, verbose_name='Tolerancia Salida Temprana (min)')),
                ('color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Color del Turno')),
                ('icon', models.CharField(default='fas fa-sun', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Orden')),
                ('work_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='attendance.workschedule', verbose_name='Horario de Trabajo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['work_schedule', 'order', 'start_time'],
                'unique_together': {('work_schedule', 'order')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('rotation_pattern', models.TextField(blank=True, help_text='JSON con patrón de rotación específico', verbose_name='Patrón de Rotación')),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='ACTIVE', max_length=20, verbose_name='Estado')),
                ('is_primary_shift', models.BooleanField(default=True, verbose_name='Turno Principal')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee', verbose_name='Empleado')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='attendance.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turnos',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'shift', 'start_date')},
            },
        ),
    ]
