# Generated by Django 5.2.6 on 2025-09-27 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_add_shift_models'),
    ]

    operations = [
    ]
