# Generated by Django 5.2.6 on 2025-10-02 02:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_add_shift_codes_fields'),
        ('departments', '0001_initial'),
        ('employees', '0002_alter_employee_address_alter_employee_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(blank=True, max_length=20, verbose_name='Código Empleado')),
                ('project', models.CharField(blank=True, help_text='Proyecto o cliente asignado', max_length=100, verbose_name='Proyecto')),
                ('leave_type', models.CharField(choices=[('medical_disability', 'Incapacidad Médica'), ('medical_appointment', 'Cita Médica'), ('medical_emergency', 'Emergencia Médica'), ('domestic_calamity', 'Calamidad Doméstica'), ('personal_matter', 'Asunto Personal'), ('personal_errand', 'Diligencia Personal'), ('marriage_permit', 'Permiso Matrimonio'), ('bereavement', 'Duelo Familiar'), ('study_permit', 'Permiso Estudio'), ('academic_exam', 'Examen Académico'), ('training', 'Capacitación'), ('court_summons', 'Citación Judicial'), ('legal_procedure', 'Trámite Legal'), ('mandatory_appearance', 'Comparecencia Obligatoria'), ('paid_leave', 'Permiso Remunerado'), ('compensatory_day', 'Día Compensatorio'), ('special_license', 'Licencia Especial'), ('unpaid_leave', 'Licencia No Remunerada'), ('vacation', 'Vacaciones')], max_length=30, verbose_name='Tipo de Ausencia')),
                ('permission_mode', models.CharField(choices=[('DAYS', 'Por Días'), ('HOURS', 'Por Horas')], default='DAYS', max_length=10, verbose_name='Modo de Permiso')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha Desde')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha Hasta')),
                ('total_days', models.IntegerField(default=0, verbose_name='Total Días')),
                ('permission_date', models.DateField(blank=True, help_text='Para permisos por horas', null=True, verbose_name='Fecha del Permiso')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora Desde')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora Hasta')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Horas')),
                ('reason_description', models.TextField(help_text='Explique brevemente el motivo de la ausencia', verbose_name='Descripción del Motivo')),
                ('supporting_document', models.FileField(blank=True, help_text='Certificado, constancia, etc.', null=True, upload_to='leave_requests/%Y/%m/', verbose_name='Documento de Soporte')),
                ('ai_generated', models.BooleanField(default=False, help_text='Si Dr. Claude auto-llenó este formulario', verbose_name='Generado por IA')),
                ('ai_confidence', models.FloatField(default=0.0, help_text='Nivel de confianza de Dr. Claude (0.0 - 1.0)', verbose_name='Confianza IA')),
                ('ai_recommendation', models.CharField(blank=True, help_text='Recomendación de Dr. Claude', max_length=100, verbose_name='Recomendación IA')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending_supervisor', 'Pendiente Jefe'), ('approved_supervisor', 'Aprobado por Jefe'), ('rejected_supervisor', 'Rechazado por Jefe'), ('pending_hr', 'Pendiente RRHH'), ('approved_hr', 'Aprobado por RRHH'), ('rejected_hr', 'Rechazado por RRHH'), ('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='draft', max_length=30, verbose_name='Estado')),
                ('employee_signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Firma Empleado')),
                ('supervisor_signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Firma Jefe')),
                ('hr_signature_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Firma RRHH')),
                ('supervisor_comments', models.TextField(blank=True, verbose_name='Comentarios del Jefe')),
                ('supervisor_decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Decisión Jefe')),
                ('hr_comments', models.TextField(blank=True, verbose_name='Comentarios de RRHH')),
                ('hr_decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Decisión RRHH')),
                ('affects_shifts', models.BooleanField(default=True, help_text='Si esta ausencia afecta turnos asignados', verbose_name='Afecta Turnos')),
                ('shifts_affected', models.JSONField(default=list, help_text='IDs de turnos afectados', verbose_name='Turnos Afectados')),
                ('requires_coverage', models.BooleanField(default=False, help_text='Si se necesita cubrir el turno', verbose_name='Requiere Reemplazo')),
                ('request_number', models.CharField(blank=True, help_text='Código único de la solicitud', max_length=20, unique=True, verbose_name='Número de Solicitud')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Área/Departamento')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='Empleado')),
                ('hr_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por RRHH')),
                ('immediate_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_leave_requests', to='employees.employee', verbose_name='Jefe Inmediato')),
                ('medical_leave', models.ForeignKey(blank=True, help_text='Vinculado si fue generado por Dr. Claude', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_request', to='attendance.medicalleave', verbose_name='Permiso Médico IA')),
                ('replacement_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_leaves', to='employees.employee', verbose_name='Empleado Reemplazo')),
                ('supervisor_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por Jefe')),
            ],
            options={
                'verbose_name': 'Solicitud de Ausencia',
                'verbose_name_plural': 'Solicitudes de Ausencia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='attendance__employe_a2f1b5_idx'), models.Index(fields=['leave_type', 'status'], name='attendance__leave_t_bb6c14_idx'), models.Index(fields=['-created_at'], name='attendance__created_bca101_idx')],
            },
        ),
    ]
