# Generated by Django 5.2.6 on 2025-10-06 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_leaverequest'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # SecurityPhoto Model
        migrations.CreateModel(
            name='SecurityPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='security_photos/%Y/%m/%d/', verbose_name='Foto')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='security_photos/thumbnails/%Y/%m/%d/', verbose_name='Miniatura')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Dirección')),
                ('capture_type', models.CharField(choices=[('AUTO', 'Automática'), ('MANUAL', 'Manual'), ('ATTENDANCE', 'Marcación'), ('ALERT', 'Alerta'), ('REQUEST', 'Solicitud Operaciones')], default='AUTO', max_length=20, verbose_name='Tipo de Captura')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('device_info', models.TextField(blank=True, verbose_name='Info del Dispositivo')),
                ('ai_analyzed', models.BooleanField(default=False, verbose_name='Analizado por IA')),
                ('ai_analysis_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Análisis IA')),
                ('ai_results', models.JSONField(blank=True, default=dict, verbose_name='Resultados IA')),
                ('has_alerts', models.BooleanField(default=False, verbose_name='Tiene Alertas')),
                ('alert_level', models.CharField(choices=[('NONE', 'Sin Alerta'), ('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='NONE', max_length=20, verbose_name='Nivel de Alerta')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_photos', to='employees.employee')),
                ('work_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.workarea')),
            ],
            options={
                'verbose_name': 'Foto de Seguridad',
                'verbose_name_plural': 'Fotos de Seguridad',
                'ordering': ['-timestamp'],
                'indexes': [
                    models.Index(fields=['employee', '-timestamp'], name='attendance_employe_idx001'),
                    models.Index(fields=['work_area', '-timestamp'], name='attendance_work_ar_idx001'),
                    models.Index(fields=['has_alerts', '-timestamp'], name='attendance_has_ale_idx001'),
                    models.Index(fields=['ai_analyzed'], name='attendance_ai_anal_idx001'),
                ],
            },
        ),
        
        # SecurityAlert Model
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('AI_DETECTION', 'Detección IA'), ('GEOFENCE', 'Geocerca'), ('PANIC', 'Botón de Pánico'), ('MANUAL', 'Manual'), ('BEHAVIOR', 'Comportamiento')], max_length=20, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=20, verbose_name='Severidad')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('ai_data', models.JSONField(blank=True, default=dict, verbose_name='Datos IA')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ACKNOWLEDGED', 'Reconocida'), ('IN_PROGRESS', 'En Progreso'), ('RESOLVED', 'Resuelta'), ('FALSE_ALARM', 'Falsa Alarma')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconocida en')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta en')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='Notas de Resolución')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_alerts', to='employees.employee')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='attendance.securityphoto')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Alerta de Seguridad',
                'verbose_name_plural': 'Alertas de Seguridad',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['employee', '-created_at'], name='attendance_employe_idx002'),
                    models.Index(fields=['status', '-created_at'], name='attendance_status__idx001'),
                    models.Index(fields=['severity', '-created_at'], name='attendance_severit_idx001'),
                ],
            },
        ),
        
        # VideoSession Model
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_name', models.CharField(max_length=100, unique=True, verbose_name='Canal')),
                ('employee_token', models.TextField(verbose_name='Token Empleado')),
                ('requester_token', models.TextField(verbose_name='Token Solicitante')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('ACTIVE', 'Activo'), ('ENDED', 'Finalizado'), ('REJECTED', 'Rechazado'), ('TIMEOUT', 'Tiempo Agotado')], default='REQUESTED', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado')),
                ('duration_seconds', models.IntegerField(default=0, verbose_name='Duración (seg)')),
                ('recording_url', models.URLField(blank=True, verbose_name='URL Grabación')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sessions', to='employees.employee')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_videos', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Sesión de Video',
                'verbose_name_plural': 'Sesiones de Video',
                'ordering': ['-created_at'],
            },
        ),
    ]
